<?php


/**
 * Skeleton subclass for representing a row from the 'phpml_lists' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * wto, 30 mar 2010, 12:39:56
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PhpMailerNewsletterPlugin.lib.model
 */
class PhpmlLists extends BasePhpmlLists {

} // PhpmlLists
