<?php


/**
 * Skeleton subclass for performing query and update operations on the 'phpml_members' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * wto, 30 mar 2010, 12:39:56
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PhpMailerNewsletterPlugin.lib.model
 */
class PhpmlMembersPeer extends BasePhpmlMembersPeer {

  static public function addEmailToPhpMailerDatabase($email) {
    $phpMailerList = PhpmlListsQuery::create()->orderByListid()->findOne();
    if(PhpmlMembersQuery::create()->filterByEmail($email)->count()) {
      return;
    }
    $phpMailerMember = new PhpmlMembers();
    $phpMailerMember->setApproved(true);
    $phpMailerMember->setEmail($email);
    $phpMailerMember->setListid($phpMailerList->getListid());
    return $phpMailerMember->save();
  }
  
} // PhpmlMembersPeer
